### ISSUE TITLE
Its not installing properlly in openedx with Tutor Maple

### ISSUE THREAD

**Issue by manojkumarhr** [teltek/PuMuKIT2-open-edx-bundle#10]
It gives error and not installing properlly in Edx tutor please resolve the issue

**Comment by manojkumarhr** [comment]
Step 85/101 : COPY --chown=app:app ./themes/ /openedx/themes/
 ---> eb49c7b9c9ff
Step 86/101 : RUN openedx-assets themes     && openedx-assets collect --settings=tutor.assets     && rdfind -makesymlinks true -followsymlinks true /openedx/staticfiles/
 ---> Running in 618ed3a3126b
python manage.py lms --settings=tutor.assets collectstatic --ignore "fixtures" --ignore "karma_*.js" --ignore "spec" --ignore "spec_helpers" --ignore "spec-helpers" --ignore "xmodule_js" --ignore "geoip" --ignore "sass" --noinput > /dev/null
Unable to load XBlock 'pumukit2'
Traceback (most recent call last):
  File "/openedx/venv/lib/python3.8/site-packages/xblock/plugin.py", line 141, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/openedx/venv/lib/python3.8/site-packages/xblock/plugin.py", line 70, in _load_class_entry_point
    class_ = entry_point.load()
  File "/openedx/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/openedx/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/openedx/venv/lib/python3.8/site-packages/pumukit2/__init__.py", line 1, in <module>
    from .pumukit2 import Pumukit2XBlock
  File "/openedx/venv/lib/python3.8/site-packages/pumukit2/pumukit2.py", line 11, in <module>
    from .utils import get_manager_url, get_iframe_url, get_api_video_url, get_personal_recorder_url, get_upload_url
  File "/openedx/venv/lib/python3.8/site-packages/pumukit2/utils.py", line 5, in <module>
    import pumukit2_settings
ModuleNotFoundError: No module named 'pumukit2_settings'

**Comment by manojkumarhr** [comment]
@Yurujai, @Alfro, @rubenrua please guide me
